### ISSUE TITLE
MassEdit note to be updated as it is no longer in preview

### ISSUE THREAD

**Issue by santipalacios2002** [Dynatrace/BizOpsConfigurator#16]
https://dynatrace.github.io/BizOpsConfigurator/#MassEdit  

* Note: this requires a Preview feature to be enabled, see: Preview  (no longer in preview https://www.dynatrace.com/news/blog/manage-thousands-of-hosts-with-centralized-large-scale-oneagent-life-cycle-management/)

**Comment by LucasHocker** [comment]
Removed outdated notices
