### ISSUE TITLE
The ! character is not being escaped

### ISSUE THREAD

**Issue by TechShady** [Dynatrace/BizOpsConfigurator#18]
I have a swap called ${conversionMessage}. The contents are: usersession.stringProperties.bookingmessage23="Your journey was booked successfully! Open the summary and print out the ticket's."

The result is:

usersession.stringProperties.bookingmessage23%3D%22Your%20journey%20was%20booked%20successfully!%20Open%20the%20summary%20and%20print%20out%20the%20ticket's.

It should be:

usersession.stringProperties.bookingmessage23%3D%22Your%20journey%20was%20booked%20successfully%21%20Open%20the%20summary%20and%20print%20out%20the%20ticket's.

**Comment by LucasHocker** [comment]
Issue was actually with Powerups, not Configurator. Changed regex in argsplit to allow for ! in URL parameters.
