### ISSUE TITLE
HostUnit Report Source

### ISSUE THREAD

**Issue by interceptor** [Dynatrace/BizOpsConfigurator#20]
Hello Lucas,

I would love to have the source for the HostUnit Report, I think it is not in this repo. It would be very useful to me instead of implementing this one from scratch. Thank you for your cool work!

Michael

**Comment by LucasHocker** [comment]
Hi Michael,
Unfortunately, the HostUnit report is kind of woven into a couple places. See:
- `/html/miscTools/HUreport.html` has the html for it
- `/js/inputChangeHandlers.js` function `HUreportChangeHandler()` has the interactivity for it
- `/js/dtAPI.js` function `getHosts()` calls the API

Hopefully that helps!
-Lucas

**Comment by interceptor** [comment]
I will look into it, thanks a lot for the hints :)
