### ISSUE TITLE
Add 'SLO' to DT Config Pusher widget

### ISSUE THREAD

**Issue by popecruzdt** [Dynatrace/BizOpsConfigurator#23]
Add the option to create SLO configuration using the DT Config Pusher widget.

**Comment by LucasHocker** [comment]
Completed.
<img width="472" alt="Screen Shot 2022-03-24 at 11 13 29 AM" src="https://user-images.githubusercontent.com/34926264/159961318-0ddc5e57-5031-4a4b-95c3-ee9d4c9b075a.png">
