### ISSUE TITLE
Add dashboard tag as workflow filter option

### ISSUE THREAD

**Issue by popecruzdt** [Dynatrace/BizOpsConfigurator#25]
The workflow selector currently enables you to group by "Persona/Use Case", "Owner / Repo", or "All".  Request for enhancement to group by tag that exists on the overview (primary) dashboard located in the JSON configuration file.  The use case being, show me all workflows related to Kubernetes... or Real User Monitoring... or Mobile, etc.

**Comment by LucasHocker** [comment]
Completed.
<img width="1033" alt="Screen Shot 2022-03-24 at 11 12 07 AM" src="https://user-images.githubusercontent.com/34926264/159961064-f5200d5e-dfa1-4182-b6de-c63a6e7dbb02.png">
