### ISSUE TITLE
Need journey.methods for Mobile UAs

### ISSUE THREAD

**Issue by TechShady** [Dynatrace/BizOpsConfigurator#4]
The UJ widget doesn't get the methods for Mobile UAs. They are null...

![image](https://user-images.githubusercontent.com/21313331/98572604-cf5d7200-2283-11eb-964b-4686e8c0a8b3.png)

**Comment by LucasHocker** [comment]
Not a Configurator issue, limitation of DT API:
```
"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"meIdentifier","message":"Application baseline export is only supported for application (`APPLICATION`) entities. It is not supported for mobile (`MOBILE_APPLICATION`) and custom (`CUSTOM_APPLICATION`) applications."
```
Recommend posting on https://answers.dynatrace.com instead.
