### ISSUE TITLE
Dashboard IDs in icon links aren't being swapped out

### ISSUE THREAD

**Issue by TechShady** [Dynatrace/BizOpsConfigurator#6]
Here's an example of my icon json:

!PU(svg):icon=analyze;link=lnk2;base=low;warn=25;crit=50;url=#dashboard;id=2662ddb8-dd6a-4345-a1bc-7ff069eda505

**Comment by LucasHocker** [comment]
Added secondary RE to search for sub-dashboard links inside PowerUps. 2nd RE: /!PU[^ ]+url=[^ ]+id=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/g
