### ISSUE TITLE
New widget request

### ISSUE THREAD

**Issue by TechShady** [Dynatrace/BizOpsConfigurator#7]
Need a markdown tile that displays app names ${app-1.name}, ${app-2.name}, etc for reference. This is needed in order to add the correct thresholds that are aligned to the correct app.

**Comment by LucasHocker** [comment]
Complete.
<img width="357" alt="Screen Shot 2021-02-17 at 8 59 02 PM" src="https://user-images.githubusercontent.com/34926264/108298871-46e44c80-7163-11eb-8028-2a45904a9eb4.png">
<img width="343" alt="Screen Shot 2021-02-17 at 8 58 50 PM" src="https://user-images.githubusercontent.com/34926264/108298880-4b106a00-7163-11eb-9647-6735526a72d7.png">
